stages:
  - Build
  - Deploy

before_script:
  - source ~/.aws_profile
  
build:
  stage: Build
  script:
    - npm install
    - npm run build
    - aws s3 rm s3://calheers-build-outputs-us-west-1/lw-shopandcompare/$CI_COMMIT_SHA --recursive
    - aws s3 cp build s3://calheers-build-outputs-us-west-1/lw-shopandcompare/$CI_COMMIT_SHA/lw-shopandcompare --recursive
  only:
    - /^dev-.*$/
    - /^rc-.*$/
    - master
  tags:
    - aws

deploy_dev:
  stage: Deploy
  script:
    - deploy-react
  environment:
    name: Dev
  only:
    - /^dev-.*$/
  tags:
    - aws

deploy_at:
  stage: Deploy
  script:
    - deploy-react
  environment:
    name: AT
  when: manual
  only:
    - /^dev-.*$/
  tags:
    - aws

deploy_test:
  stage: Deploy
  script:
    - deploy-react
  environment:
    name: Test
  only:
    - /^rc-.*$/
  tags:
    - aws

deploy_load:
  stage: Deploy
  script:
    - deploy-react
  environment:
    name: Load
  when: manual
  only:
    - /^rc-.*$/
  tags:
    - aws

deploy_prod:
  stage: Deploy
  script:
    - deploy-react
  environment:
    name: Prod
  when: manual
  only:
    - master
  tags:
    - aws

deploy_post-prod:
  stage: Deploy
  script:
    - deploy-react
  environment:
    name: Post-Prod
  when: manual
  only:
    - master
  tags:
    - aws
